### ISSUE TITLE
Claymore-Miner-Gui first usage

### ISSUE THREAD

**Issue by imrecsoka** [acdop100/Claymore-Miner-Gui#1]
Hi, i am no expert with mining and still trying to learn this stuff.
I am going to have to install Python im guessing?
Which version do you recommend?
Then do i simply just double click your .py file in windows 7?

**Comment by acdop100** [comment]
The computers which I have tested this on all had python and has not been tested otherwise, so let us assume yes. I recommend the latest version of Python 3 (I think Python 3.6? Thats what I used). The best way to run it is to open up a CMD window in Windows and drag the file into it.

**Comment by imrecsoka** [comment]
Okay so in windows CMD and then gooi the .py file in there and run it.
Of course python will have to be installed else windows will look at me funny.
Right?

**Comment by acdop100** [comment]
I believe that is correct, yes. Install python, then drag the file into a CMD window.

**Comment by imrecsoka** [comment]
Great i will get to it when i get to it.
Oh sorry one more thing though, which algorithm does it support, i never understand this properly.
So this is basically going to tell  me what coin to mine right ?
I am really struggling with a tool called SGMiner.exe it is such a pain to use because it does not show what algorithms it uses .....   so for example if i type Sgminer.exe --algo=hello , it doesnt fail with a message saying why it failed or anything else even, it just goes back to the prompt and the screen gets cleared, i really dont understand the point and pleasure in a utility like this.

**Comment by acdop100** [comment]
This is specifically to be used to with Claymore's miners. His miners are specific to a certain algorithm (Be that Ethereum, Zcash, etc). This program does not have support for SGMiner.

**Comment by imrecsoka** [comment]
Hi,


Oh yes right i forgot, this is a GUI, sorry i forgot.


Well im looking forward to it, i hope it makes my life easier.


Regards

Imre


________________________________
